<?php
/** @var \Hyva\Theme\Model\ViewModelRegistry $viewModels */
$heroiconsViewModel = $viewModels->require(Hyva\Theme\ViewModel\HeroiconsOutline::class);
$stepBlockCurrent = $block->getChildBlock($magewire->getStepBlockNameInLayout());
?>
<div class="flex flex-col">
    <header class="flex space-x-4">
        <h1 class="text-xl">Step: <?= $magewire->getStep() ?> / <?= $magewire->getTotalSteps() ?></h1>

        <?php if ($magewire->getStep() > 1): ?>
        <button wire:click="restart">
            <?= $heroiconsViewModel->refreshHtml() ?>
        </button>
        <?php endif ?>
    </header>

    <section>
        <?= $stepBlockCurrent->toHtml() ?>
    </section>

    <nav class="my-6 flex space-x-4">
        <?php if ($magewire->canMove($magewire->getStep() + 1)): ?>
        <button wire:click="navigate" class="btn btn-primary">
            Move to step <span class="font-bold ml-4 bg-white rounded-full text-black w-6 h-6"><?= $magewire->getStep() + 1 ?></span>
        </button>
        <?php endif ?>

        <?php if ($magewire->getStep() > 1): ?>
        <button wire:click="navigate(<?= $magewire->getStep() - 1 ?>)" class="btn btn-secondary">
            Back
        </button>
        <?php endif ?>
    </nav>
</div>
